yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    # регистрация и авторизация
    path('auth/', include('users.urls')),

    # если нужного шаблона для /auth не нашлось в файле users.urls —
    # ищем совпадения в файле django.contrib.auth.urls
    path('auth/', include('django.contrib.auth.urls')),

    # раздел администратора
    path('admin/', admin.site.urls),

    # обработчик для главной страницы ищем в urls.py приложения posts
    path("", include('posts.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

yatube/templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
      <a href="{% url 'about:author' %}">Об авторе</a>
      <a href="{% url 'about:tech' %}">Технологии</a>
    </p>
    <p class="m-0 text-dark text-center ">
      Социальная сеть <span style="color:red">Ya</span>tube © {% now "Y" %}, все права защищены.
    </p>
</footer> 

yatube/templates/includes/menu.html
{% if user.is_authenticated %}
  <div class="row">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">
          Все авторы
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow_index' %}">
          Избранные авторы
        </a>
      </li>
    </ul>
  </div>
{% endif %}

yatube/templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="{% url 'index' %}"><span style="color:red">Ya</span>tube</a>
  <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
      Пользователь: {{ user.username }}.
      <a class="p-2 text-dark" href="{% url 'new_post' %}">Создать запись</a>
      <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
    {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
    {% endif %}
  </nav>
</nav>

yatube/templates/includes/paginator.html
{# Отрисовывает навигацию паджинатора только если #}
{# все посты не помещаются на первую страницу, если есть другие страницы #}
{% if page.has_other_pages %}
  <nav>
    <ul class="pagination">
      {% if page.has_previous %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">&laquo; Предыдущая</span>
        </li>
      {% endif %}
      {% for i in page.paginator.page_range %}
        {% if page.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">(текущая)</span>
            </span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if page.has_next %}
        <li class="page-item">
          <a
            class="page-link"
            href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <span class="page-link">Следующая &raquo;</span>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

yatube/templates/includes/post_item.html
{% load thumbnail %}
<!-- Пост -->
      <div class="card mb-3 mt-1 shadow-sm">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img" src="{{ im.url }}">
        {% endthumbnail %}
        <div class="card-body">
          <p class="card-text">
            <!-- Ссылка на страницу автора через @ -->
            <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
              <strong class="d-block text-gray-dark">
                @{{ post.author }}
              </strong>
            </a>
            <!-- Текст поста -->
            {{ post.text|linebreaksbr }}
          </p>
          <!-- Отображение ссылки на группу через # -->
          {% if post.group %}
            <a class="card-link muted" href="{% url 'group' post.group.slug %}">
              <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
            </a>
          {% endif %}
          <!-- Отображение ссылки на комментарии -->
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              {% if post.comments.exists %}
                <a class="btn btn-sm text-muted" href="{% url 'post' username=post.author.username post_id=post.id %}" role="button">
                  Комментариев: {{ post.comments.count }}
                </a>
              {% endif %}
              {% if not add_comment %}
              <a class="btn btn-sm text-muted" href="{% url 'add_comment' username=post.author.username post_id=post.id %}" role="button">
                Добавить комментарий
              </a>
              {% endif %}
              <!-- Ссылка на редактирование, показывается только автору записи. -->
              {% if post.author == request.user %}
              <a class="btn btn-sm text-muted" href="{% url 'post_edit' username=post.author.username post_id=post.id %}" role="button">
                Редактировать
              </a>
              {% endif %}
            </div>
            <!-- Дата публикации  -->
            <small class="text-muted">{{ post.pub_date|date:"d M Y" }}</small>
          </div>  
        </div>
      </div>

yatube/templates/includes/profile_card.html
<div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <div class="h2">
            <!-- Имя автора -->
            {{ author.get_full_name }}
          </div>
          <div class="h3 text-muted">
            <!-- username автора -->
            @{{ author.get_username }}
          </div>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="h6 text-muted">
              Подписчиков: {{ followers_statics.followers_count }} <br>
              Подписан: {{ followers_statics.follows_count }}
            </div>
          </li>
          <li class="list-group-item">
            <div class="h6 text-muted">
              <!--Количество записей -->
              Записей: {{ author.posts.count }}
            </div>
          </li>
          {% if not request.user == author %}
          <li class="list-group-item">
            {% if following %}
              <a
                class="btn btn-lg btn-light"
                href="{% url 'profile_unfollow' author.username %}" role="button">
                Отписаться
              </a>
            {% else %}
              <a
                class="btn btn-lg btn-primary"
                href="{% url 'profile_follow' author.username %}" role="button">
                Подписаться
              </a>
            {% endif %}
          </li>
          {% endif %}
        </ul>
      </div>
    </div>